[package]
name = "mpf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.3.3"

anyhow = "1.0.58"

procfs="0.12.0"
clap = { version = "3.2.12", features = ["derive"] }

serde = "1.0.139"
serde_derive = "1.0.139"
serde_json = "1.0.82"
human-panic = "1.0.3"
